bot:
  commandPrefix: "!"
  # please always put token in "" 
  token: "token"
  
atlassian:
  jiraUrl: "https://jira.mydomain.com"
  confluenceUrl: "https://confluence.mydomain.com"
  username: "Bob"
  password: "bobsSecurePassword1337"